"use client";
import { useState } from "react";
import Head from "next/head";
import { AiFillLinkedin, AiFillGithub, AiFillHtml5 } from "react-icons/ai";
import {
  BiLogoCss3,
  BiLogoJavascript,
  BiLogoReact,
  BiLogoTailwindCss,
} from "react-icons/bi";
import { BsFillMoonStarsFill } from "react-icons/bs";
import developedbynzo from "../public/developedbynzo.jpg";
import dev_web from "../public/dev_web.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section id="accueil" className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl dark:text-teal-400 md:text-lg">
              Enzo.dev
            </h1>
            <ul className="flex items-center space-x-6">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="#accueil"
                  className="font-burtons dark:text-teal-400 md:text-lg"
                >
                  Accueil
                </a>
              </li>
              <li>
                <a
                  href="#about"
                  className="font-burtons dark:text-teal-400 md:text-lg"
                >
                  A propos
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="font-burtons dark:text-teal-400 md:text-lg"
                >
                  Projets
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="font-burtons dark:text-teal-400 md:text-lg"
                >
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Enzo Six
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Développeur Web.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Salut, je suis Enzo Six. Un passionné de développement web. Développeur basé dans la commune d'Aubin, France 📍.
            </p>
            <div className="text-4xl flex justify-center gap-16 py-3 text-black dark:text-gray-400">
              <a href="https://www.linkedin.com/in/enzo-six-8b5727267/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Enzo-six">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-48 h-48 relative overflow-hidden mt-14 md:h-64 md:w-64">
              <Image src={developedbynzo} layout="fill" objectFit="cover" />
            </div>
            <div className="text-4xl flex justify-center items-center py-3 mt-10 gap-7 text-black dark:text-gray-400">
              <h4 className="text-2xl m-0 p-0 text-black dark:text-gray-400">
                Compétences
              </h4>
              <div className="border-r border-black h-8 dark:text-gray-400"></div>
              <AiFillHtml5 />
              <BiLogoCss3 />
              <BiLogoJavascript />
              <BiLogoReact />
              <BiLogoTailwindCss />
            </div>
          </div>
          </section>
          <section id="about" className="min-h-screen">
          <div className="text-center p-5 py-5">
            <h1 className="text-4xl text-teal-600 font-medium dark:text-teal-400 md:text-5xl">
              A propos de moi
            </h1>
            <div class="grid gap-1 grid-cols-2 grid-rows-1 p-36">
            <Image src={dev_web} className="ml-56 w-60 h-60 md:w-72 md:h-72 rounded-md"/>
            <p>test</p>
            </div>
  </div>
</section>
      </main>
    </div>
  );
}